# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Hugoma"
license = "MIT"
licenselink = "https://github.com/fvcproductions/hugoma/blob/master/LICENSE"
description = "A starter theme for Hugo created with Bulma and optimized with modern workflows and tooling. 🌟️"
homepage = "https://github.com/fvcproductions/hugoma"
tags = ["minimal", "bulma", "responsive"]
features = ["contact", "speaking", "cards"]
min_version = "0.31"

[author]
  name = "Frances Coronel"
  homepage = "https://www.fvcproductions.com"
