baseURL                       = "https://hugoma.fvcproductions.com"
title                         = "Hugoma Theme"

assetDir                      = "src"
enableEmoji                   = true
enableRobotsTXT               = true
footnoteReturnLinkContents    = "↩"
metaDataFormat                = "yaml"
# theme                         = "hugoma"

# Language
languageCode                  = "en-us"
defaultContentLanguage        = "en"

# Code
pygmentsCodefences            = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle                 = "manni"

# Internal Templates
googleAnalytics               = "UA-63190978-3"
disqusShortname               = "fvcproductions"

# Pagination
Paginate                      = 6
PaginatePath                  = "adventures"

# Categories
preserveTaxonomyNames         = false

# RSS
[outputs]
    home                      = ["HTML", "AMP", "RSS"]
    page                      = ["HTML", "AMP"]

# Output Formats
[outputFormats]
    [outputFormats.RSS]
        mediatype             = "application/rss"
        baseName              = "feed"

# SEO
# og_image - image when shown when shared on social media
[params]
    description               = "A starter theme for Hugo created with Bulma and optimized with modern workflows and tooling. 🌟️"
    copyright                 = "FVCproductions"
    year                      = 2018
    og_image                  = "https://i.imgur.com/mGA3X7m.png"
    logo                      = "/assets/img/favicons/128x128.png"
    github                    = "fvcproductions/hugoma-theme"
    search_url                = "https://www.fvcproductions.com/search/#gsc.tab=0&gsc.q={search_term_string}"
    # set to false to hide the Contributions footer
    contributions             = true
    # OneSignal
    one_signal_id             = "e64fce8d-6d54-4434-8b76-3fde80e6bdf1"

# Permalinks
[permalinks]
    blog                      = "/blog/:year/:month/:day/:title/"
    portfolio                 = "/portfolio/:year/:month/:day/:title/"

# Author
[author]
    name                      = "Frances Coronel"
    copyright                 = "©️ FVCproductions"
    email                     = "hello@fvcproductions.com"

# Social Links
[social]
    facebook                  = "frances.v.coronel"
    instagram                 = "fvcproductions"
    linkedin                  = "fvcproductions"
    google_plus               = "+fvcproductions2013"
    twitter                   = "fvcproductions"
    youtube                   = "+fvcproductions2013"

# Menu
# name - name of menu item
# url - route of menu item (can be external)
# identifier - Font Awesome Icon you want shown

# Mobile Menu
# Shown on Mobile
# Hidden on Desktop
[[menu.mobile]]
    name                      = "GitHub"
    url                       = "https://github.com/fvcproductions/hugoma-theme"
    identifier                = "github"
[[menu.mobile]]
    name                      = "Twitter"
    url                       = "https://twitter.com/fvcproductions"
    identifier                = "twitter"
# [[menu.mobile]]
#     name                    = "LinkedIn"
#     url                     = "https://linkedin.com/in/fvcproductions"
#     identifier              = "linkedin"

# Desktop Menu (Right)
# Shown on Desktop
# Hidden on Mobile
[[menu.right]]
    name                      = "GitHub"
    url                       = "https://github.com/fvcproductions/hugoma-theme"
    identifier                = "github"
[[menu.right]]
    name                      = "Twitter"
    url                       = "https://twitter.com/fvcproductions"
    identifier                = "twitter"

# Desktop Menu (Left)
# Turns into hamburger menu on mobile
[[menu.left]]
    name                      = "About 😊"
    url                       = "/about/"
[[menu.left]]
    name                      = "Archive 🕒"
    url                       = "/archive/"
[[menu.left]]
    name                      = "Blog 📝"
    url                       = "/blog/"
[[menu.left]]
    name                      = "Contact 📥"
    url                       = "/contact/"
# [[menu.left]]
#     name                    = "Getting Started 🌟️"
#     url                     = "/getting-started/"
[[menu.left]]
    name                      = "Portfolio 💼"
    url                       = "/portfolio/"
[[menu.left]]
    name                      = "Search 🔍️"
    url                       = "/search/"
[[menu.left]]
    name                      = "Speaking 💬️"
    url                       = "/speaking/"

[taxonomies]
    category                  = "categories"
    tag                       = "tags"
